FROM gcr.io/distroless/static@sha256:9b60270ec0991bc4f14bda475e8cae75594d8197d0ae58576ace84694aa75d7a

ENTRYPOINT [ "/bin/${BINARY_NAME}" ]
COPY _output/local/bin/linux/amd64/${BINARY_NAME} /bin/${BINARY_NAME}

USER 65534
